In [1]:
import cntk as C
import numpy as np
import math
np.set_printoptions(precision=4)

features = C.input_variable(3)
label = C.input_variable(2)
z = C.layers.Sequential([C.layers.Dense(4, activation=C.relu), C.layers.Dense(2)])(features)

In [116]:
sgd_learner_m = C.sgd(z.parameters, lr = 0.5, minibatch_size = C.learners.IGNORE)
sgd_learner_s2 = C.sgd(z.parameters, lr = 0.5, minibatch_size = 2)
lr = 0.01
# sgd_learner_m = C.sgd(z.parameters, lr=C.learners.learning_parameter_schedule_per_sample(lr))


In [104]:

loss = C.squared_error(z, label)
sgd_learner_my1 = C.sgd(z.parameters, lr=C.learners.learning_parameter_schedule([lr]*2+[lr/2]*3+[lr/4], epoch_size=2000))
x_train = np.asarray(np.random.rand(100,3), dtype=np.float32)
y_train = np.asarray(np.random.rand(100,2), dtype=np.float32)
progress_writer = C.logging.ProgressPrinter()
loss.train((x_train, y_train), minibatch_size=10, max_epochs=5, parameter_learners=[sgd_learner_my1], callbacks=[progress_writer])

Learning rate per minibatch: 0.01
Finished Epoch[1]: loss = 0.176705 * 100, metric = 0.00% * 100 0.028s (3571.4 samples/s);
Finished Epoch[2]: loss = 0.175672 * 100, metric = 0.00% * 100 0.014s (7142.9 samples/s);
Finished Epoch[3]: loss = 0.174976 * 100, metric = 0.00% * 100 0.018s (5555.6 samples/s);
Finished Epoch[4]: loss = 0.174506 * 100, metric = 0.00% * 100 0.015s (6666.7 samples/s);
Finished Epoch[5]: loss = 0.174188 * 100, metric = 0.00% * 100 0.014s (7142.9 samples/s);


{'epoch_summaries': [{'loss': 0.17670473098754882,
   'metric': 0.0,
   'samples': 100},
  {'loss': 0.1756724548339844, 'metric': 0.0, 'samples': 100},
  {'loss': 0.17497642517089843, 'metric': 0.0, 'samples': 100},
  {'loss': 0.17450614929199218, 'metric': 0.0, 'samples': 100},
  {'loss': 0.17418766021728516, 'metric': 0.0, 'samples': 100}],
 'updates': []}

In [105]:
sgd_learner_my1 = C.sgd(z.parameters, lr=C.learners.learning_parameter_schedule([lr]*2+[lr/2]*3+[lr/4], epoch_size=2000))
loss.train((x_train, y_train), max_epochs=5, parameter_learners=[sgd_learner_my1], callbacks=[progress_writer])

Learning rate per minibatch: 0.01
Finished Epoch[6]: loss = 0.173835 * 100, metric = 0.00% * 100 23.794s (  4.2 samples/s);
Finished Epoch[7]: loss = 0.173730 * 100, metric = 0.00% * 100 0.007s (14285.7 samples/s);
Finished Epoch[8]: loss = 0.173670 * 100, metric = 0.00% * 100 0.006s (16666.7 samples/s);
Finished Epoch[9]: loss = 0.173644 * 100, metric = 0.00% * 100 0.005s (20000.0 samples/s);
Finished Epoch[10]: loss = 0.173646 * 100, metric = 0.00% * 100 0.006s (16666.7 samples/s);


{'epoch_summaries': [{'loss': 0.17383459091186523,
   'metric': 0.0,
   'samples': 100},
  {'loss': 0.17373039245605468, 'metric': 0.0, 'samples': 100},
  {'loss': 0.17366983413696288, 'metric': 0.0, 'samples': 100},
  {'loss': 0.17364423751831054, 'metric': 0.0, 'samples': 100},
  {'loss': 0.17364635467529296, 'metric': 0.0, 'samples': 100}],
 'updates': []}

In [112]:
sgd_learner_my1 = C.sgd(z.parameters, lr=C.learners.learning_parameter_schedule([lr]*2+[lr/2]*3+[lr/4], epoch_size=50))
loss.train((x_train, y_train), minibatch_size=10, max_epochs=5, parameter_learners=[sgd_learner_my1], callbacks=[progress_writer])

Learning rate per minibatch: 0.01
Finished Epoch[31]: loss = 0.173491 * 100, metric = 0.00% * 100 12.481s (  8.0 samples/s);
Learning rate per minibatch: 0.005
Finished Epoch[32]: loss = 0.173328 * 100, metric = 0.00% * 100 0.015s (6666.7 samples/s);
Learning rate per minibatch: 0.0025
Finished Epoch[33]: loss = 0.173348 * 100, metric = 0.00% * 100 0.016s (6250.0 samples/s);
Finished Epoch[34]: loss = 0.173250 * 100, metric = 0.00% * 100 0.016s (6250.0 samples/s);
Finished Epoch[35]: loss = 0.173249 * 100, metric = 0.00% * 100 0.015s (6666.7 samples/s);


{'epoch_summaries': [{'loss': 0.1734906578063965,
   'metric': 0.0,
   'samples': 100},
  {'loss': 0.1733275032043457, 'metric': 0.0, 'samples': 100},
  {'loss': 0.17334751129150391, 'metric': 0.0, 'samples': 100},
  {'loss': 0.17324975967407227, 'metric': 0.0, 'samples': 100},
  {'loss': 0.17324859619140626, 'metric': 0.0, 'samples': 100}],
 'updates': []}

In [113]:
sgd_learner_my1 = C.sgd(z.parameters, lr=C.learners.learning_parameter_schedule_per_sample([lr]*2+[lr/2]*3+[lr/4], epoch_size=50))
loss.train((x_train, y_train), minibatch_size=10, max_epochs=5, parameter_learners=[sgd_learner_my1], callbacks=[progress_writer])

Learning rate per 1 samples: 0.01
Finished Epoch[36]: loss = 0.175562 * 100, metric = 0.00% * 100 34.232s (  2.9 samples/s);
Learning rate per 1 samples: 0.005
Finished Epoch[37]: loss = 0.174765 * 100, metric = 0.00% * 100 0.015s (6666.7 samples/s);
Learning rate per 1 samples: 0.0025
Finished Epoch[38]: loss = 0.174905 * 100, metric = 0.00% * 100 0.013s (7692.3 samples/s);
Finished Epoch[39]: loss = 0.173936 * 100, metric = 0.00% * 100 0.016s (6250.0 samples/s);
Finished Epoch[40]: loss = 0.173939 * 100, metric = 0.00% * 100 0.017s (5882.4 samples/s);


{'epoch_summaries': [{'loss': 0.1755621337890625,
   'metric': 0.0,
   'samples': 100},
  {'loss': 0.17476490020751953, 'metric': 0.0, 'samples': 100},
  {'loss': 0.1749051284790039, 'metric': 0.0, 'samples': 100},
  {'loss': 0.17393606185913085, 'metric': 0.0, 'samples': 100},
  {'loss': 0.17393922805786133, 'metric': 0.0, 'samples': 100}],
 'updates': []}

In [52]:
def inspect_update(learner, actual_minibatch_size, count=1):
    # Save current parameter values
    old_values = [p.value for p in learner.parameters]
#     print("old_values:")
#     print(old_values)
    # Set current parameter values to all 0
    for p in learner.parameters:
        p.value = 0 * p.value
    # create all-ones gradients, and associate the sum of gradients over
    # the number of samples in the minibatch with the parameters
    gradients_sum = {p: np.zeros_like(p.value)
                     + 1.0 * actual_minibatch_size for p in learner.parameters}
#     print("gradients_sum:")
#     print(gradients_sum)
    # do 'count' many updates
    for i in range(count):
        # note that CNTK learner's update function consumes
        # sum of gradients over the samples in a minibatch
        learner.update(gradients_sum, actual_minibatch_size)
    ret_values = [p.value for p in learner.parameters]
#     print("ret_values:")
#     print(ret_values)
    # Restore values
    for p, o in zip(learner.parameters, old_values):
        p.value = o
#     print([p.value for p in learner.parameters])
    return ret_values

In [161]:
print('\nper minibatch:\n', inspect_update(sgd_learner_m, actual_minibatch_size=10, count = 2))
print('\nper samples: \n', inspect_update(sgd_learner_s2, actual_minibatch_size=10, count = 2))


per minibatch:
 [array([[-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.]], dtype=float32), array([-1., -1.], dtype=float32), array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]], dtype=float32), array([-1., -1., -1., -1.], dtype=float32)]

per samples: 
 [array([[-5., -5.],
       [-5., -5.],
       [-5., -5.],
       [-5., -5.]], dtype=float32), array([-5., -5.], dtype=float32), array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]], dtype=float32), array([-5., -5., -5., -5.], dtype=float32)]


In [163]:
lr=0.01
sgd_learner_my1 = C.sgd(z.parameters, lr=C.learners.learning_parameter_schedule_per_sample([lr]*2+[lr/2]*3+[lr/4], epoch_size=256))
sgd_learner_my2 = C.sgd(z.parameters, lr=C.learners.learning_parameter_schedule([lr]*2+[lr/2]*3+[lr/4], epoch_size=256))
sgd_learner_my3 = C.sgd(z.parameters, lr=C.learners.learning_parameter_schedule(lr, epoch_size=10))

D:\software\Anaconda3\lib\site-packages\cntk\learners\__init__.py:340: RuntimeWarning: When providing the schedule as a number, epoch_size is ignored
  warnings.warn('When providing the schedule as a number, epoch_size is ignored', RuntimeWarning)


In [166]:

print('\nper minibatch:\n', inspect_update(sgd_learner_my1, actual_minibatch_size=256, count = 1))
print('\nper samples: \n', inspect_update(sgd_learner_my2, actual_minibatch_size=256, count = 1))
print('\nper samples: \n', inspect_update(sgd_learner_my3, actual_minibatch_size=256, count = 1))


per minibatch:
 [array([[-1.28, -1.28],
       [-1.28, -1.28],
       [-1.28, -1.28],
       [-1.28, -1.28]], dtype=float32), array([-1.28, -1.28], dtype=float32), array([[-1.28, -1.28, -1.28, -1.28],
       [-1.28, -1.28, -1.28, -1.28],
       [-1.28, -1.28, -1.28, -1.28]], dtype=float32), array([-1.28, -1.28, -1.28, -1.28], dtype=float32)]

per samples: 
 [array([[-0.005, -0.005],
       [-0.005, -0.005],
       [-0.005, -0.005],
       [-0.005, -0.005]], dtype=float32), array([-0.005, -0.005], dtype=float32), array([[-0.005, -0.005, -0.005, -0.005],
       [-0.005, -0.005, -0.005, -0.005],
       [-0.005, -0.005, -0.005, -0.005]], dtype=float32), array([-0.005, -0.005, -0.005, -0.005], dtype=float32)]

per samples: 
 [array([[-0.01, -0.01],
       [-0.01, -0.01],
       [-0.01, -0.01],
       [-0.01, -0.01]], dtype=float32), array([-0.01, -0.01], dtype=float32), array([[-0.01, -0.01, -0.01, -0.01],
       [-0.01, -0.01, -0.01, -0.01],
       [-0.01, -0.01, -0.01, -0.01]], dtype=flo

In [162]:
256*0.01/4

0.64

In [17]:
print('\nper minibatch:\n', inspect_update(sgd_learner_m, actual_minibatch_size=2))

old_values:
[array([[-1.2322, -1.2272],
       [-0.5976, -1.458 ],
       [-0.7982,  0.3227],
       [-0.5585, -1.3511]], dtype=float32), array([-0.5, -0.5], dtype=float32), array([[-1.1299,  0.4113, -1.3526, -0.3195],
       [-0.4217, -1.32  , -0.2565, -0.6415],
       [ 0.1337,  0.2523, -0.6423, -0.212 ]], dtype=float32), array([-0.5, -0.5, -0.5, -0.5], dtype=float32)]
gradients_sum:
{Parameter('W', [], [4 x 2]): array([[2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.]], dtype=float32), Parameter('b', [], [2]): array([2., 2.], dtype=float32), Parameter('W', [], [3 x 4]): array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32), Parameter('b', [], [4]): array([2., 2., 2., 2.], dtype=float32)}
ret_values:
[array([[-0.5, -0.5],
       [-0.5, -0.5],
       [-0.5, -0.5],
       [-0.5, -0.5]], dtype=float32), array([-0.5, -0.5], dtype=float32), array([[-0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5, -0.5]], dty

In [4]:
print('\nper 2 samples: \n', inspect_update(sgd_learner_s2, actual_minibatch_size=2))


per 2 samples: 
 [array([[-0.5, -0.5],
       [-0.5, -0.5],
       [-0.5, -0.5],
       [-0.5, -0.5]], dtype=float32), array([-0.5, -0.5], dtype=float32), array([[-0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5, -0.5]], dtype=float32), array([-0.5, -0.5, -0.5, -0.5], dtype=float32)]


In [53]:
print('\nper minibatch:\n', inspect_update(sgd_learner_m, actual_minibatch_size=10))
print('\nper 10 samples: \n', inspect_update(sgd_learner_s2, actual_minibatch_size=10))


per minibatch:
 [array([[-0.5, -0.5],
       [-0.5, -0.5],
       [-0.5, -0.5],
       [-0.5, -0.5]], dtype=float32), array([-0.5, -0.5], dtype=float32), array([[-0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5, -0.5]], dtype=float32), array([-0.5, -0.5, -0.5, -0.5], dtype=float32)]

per 10 samples: 
 [array([[-2.5, -2.5],
       [-2.5, -2.5],
       [-2.5, -2.5],
       [-2.5, -2.5]], dtype=float32), array([-2.5, -2.5], dtype=float32), array([[-2.5, -2.5, -2.5, -2.5],
       [-2.5, -2.5, -2.5, -2.5],
       [-2.5, -2.5, -2.5, -2.5]], dtype=float32), array([-2.5, -2.5, -2.5, -2.5], dtype=float32)]


In [33]:
mb_size = 32

lr_schedule = C.learning_parameter_schedule(1, minibatch_size=C.learners.IGNORE)
t_schedule = C.momentum_schedule(0.971, minibatch_size=C.learners.IGNORE)

sgd = C.sgd(z.parameters, lr_schedule)
tsgd = C.momentum_sgd(z.parameters, lr_schedule, t_schedule, unit_gain=False)
adadelta  = C.adadelta(z.parameters, lr_schedule, 0.999, 1e-6)
adagrad   = C.adagrad(z.parameters, lr_schedule)
adam      = C.adam(z.parameters, lr_schedule, t_schedule, unit_gain=False)
adamax    = C.adam(z.parameters, lr_schedule, t_schedule, unit_gain=False, adamax=True)
fsadagrad = C.fsadagrad(z.parameters, lr_schedule, t_schedule, unit_gain=False)
rmsprop   = C.rmsprop(z.parameters, lr_schedule, gamma=0.999, inc=1.0+1e-9, dec=1.0-1e-9, max=np.inf, min=1e-30)

num_steps = 30
print('sgd :', inspect_update(sgd, mb_size, num_steps)[0][0])
print('tsgd :', inspect_update(tsgd, mb_size, num_steps)[0][0])
print('adadelta :', inspect_update(adadelta, mb_size, num_steps)[0][0])
print('adagrad  :', inspect_update(adagrad, mb_size, num_steps)[0][0])
print('adam     :', inspect_update(adam, mb_size, num_steps)[0][0])
print('adamax   :', inspect_update(adamax, mb_size, num_steps)[0][0])
print('fsadagrad:', inspect_update(fsadagrad, mb_size, num_steps)[0][0])
print('rmsprop  :', inspect_update(rmsprop, mb_size, num_steps)[0][0])

adadelta_schedule = C.learning_parameter_schedule(1004, minibatch_size=C.learners.IGNORE)
adadelta_tuned  = C.adadelta(z.parameters, adadelta_schedule, 0.999, 1e-6)
print('adadelta2:', inspect_update(adadelta_tuned, mb_size, num_steps)[0][0])

sgd : [-30. -30.]
tsgd : [-357.4343 -357.4343]
adadelta : [-0.0297 -0.0297]
adagrad  : [-30. -30.]
adam     : [-32.3197 -32.3197]
adamax   : [-32.3276 -32.3276]
fsadagrad: [-63.1707 -63.1707]
rmsprop  : [-30. -30.]
adadelta2: [-29.7969 -29.7969]


In [6]:
[p.value for p in sgd_learner_m.parameters]

[array([[-0.7322, -0.7272],
        [-0.0976, -0.958 ],
        [-0.2982,  0.8227],
        [-0.0585, -0.8511]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.6299,  0.9113, -0.8526,  0.1805],
        [ 0.0783, -0.82  ,  0.2435, -0.1415],
        [ 0.6337,  0.7523, -0.1423,  0.288 ]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [11]:
actual_minibatch_size = 2
gradients_sum={p: np.zeros_like(p.value) + 1.0 * actual_minibatch_size for p in sgd_learner_m.parameters}
gradients_sum

{Parameter('W', [], [3 x 4]): array([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], dtype=float32),
 Parameter('W', [], [4 x 2]): array([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]], dtype=float32),
 Parameter('b', [], [2]): array([2., 2.], dtype=float32),
 Parameter('b', [], [4]): array([2., 2., 2., 2.], dtype=float32)}

In [10]:
sgd_learner_m.update(gradients_sum, actual_minibatch_size)
[p.value for p in sgd_learner_m.parameters]

[array([[-1.2322, -1.2272],
        [-0.5976, -1.458 ],
        [-0.7982,  0.3227],
        [-0.5585, -1.3511]], dtype=float32),
 array([-0.5, -0.5], dtype=float32),
 array([[-1.1299,  0.4113, -1.3526, -0.3195],
        [-0.4217, -1.32  , -0.2565, -0.6415],
        [ 0.1337,  0.2523, -0.6423, -0.212 ]], dtype=float32),
 array([-0.5, -0.5, -0.5, -0.5], dtype=float32)]

In [24]:
lr=0.01
lrs = C.learners.learning_parameter_schedule_per_sample([lr]*20+[lr/2]*30+[lr/4], epoch_size=100)


In [26]:
sgd_learner = C.sgd(z.parameters, [0.05]*3 + [0.025]*2 + [0.0125], epoch_size=100)